<option value="-11:00">Midway Island</option>
<option value="-11:00">Samoa</option>
<option value="-10:00">Hawaii</option>
<option value="-09:00">Alaska</option>
<option value="-08:00">Pacific Time (US &amp; Canada)</option>
<option value="-08:00">Tijuana</option>
<option value="-07:00">Arizona</option>
<option value="-07:00">Mountain Time (US &amp; Canada)</option>
<option value="-07:00">Chihuahua</option>
<option value="-07:00">Mazatlan</option>
<option value="-06:00">Mexico City</option>
<option value="-06:00">Monterrey</option>
<option value="-06:00">Saskatchewan</option>
<option value="-06:00">Central Time (US &amp; Canada)</option>
<option value="-05:00">Eastern Time (US &amp; Canada)</option>
<option value="-05:00">Indiana (East)</option>
<option value="-05:00">Bogota</option>
<option value="-05:00">Lima</option>
<option value="-04:30">Caracas</option>
<option value="-04:00">Atlantic Time (Canada)</option>
<option value="-04:00">La Paz</option>
<option value="-04:00">Santiago</option>
<option value="-03:30">Newfoundland</option>
<option value="-03:00">Buenos Aires</option>
<option value="-03:00">Greenland</option>
<option value="-02:00">Stanley</option>
<option value="-01:00">Azores</option>
<option value="-01:00">Cape Verde Is.</option>
<option value="">Casablanca</option>
<option value="">Dublin</option>
<option value="">Lisbon</option>
<option value="">London</option>
<option value="">Monrovia</option>
<option value="+01:00">Amsterdam</option>
<option value="+01:00">Belgrade</option>
<option value="+01:00">Berlin</option>
<option value="+01:00">Bratislava</option>
<option value="+01:00">Brussels</option>
<option value="+01:00">Budapest</option>
<option value="+01:00">Copenhagen</option>
<option value="+01:00">Ljubljana</option>
<option value="+01:00">Madrid</option>
<option value="+01:00">Paris</option>
<option value="+01:00">Prague</option>
<option value="+01:00">Rome</option>
<option value="+01:00">Sarajevo</option>
<option value="+01:00">Skopje</option>
<option value="+01:00">Stockholm</option>
<option value="+01:00">Vienna</option>
<option value="+01:00">Warsaw</option>
<option value="+01:00">Zagreb</option>
<option value="+02:00">Athens</option>
<option value="+02:00">Bucharest</option>
<option value="+02:00">Cairo</option>
<option value="+02:00">Harare</option>
<option value="+02:00">Helsinki</option>
<option value="+02:00">Istanbul</option>
<option value="+02:00">Jerusalem</option>
<option value="+02:00">Kyiv</option>
<option value="+02:00">Minsk</option>
<option value="+02:00">Riga</option>
<option value="+02:00">Sofia</option>
<option value="+02:00">Tallinn</option>
<option value="+02:00">Vilnius</option>
<option value="+03:00">Baghdad</option>
<option value="+03:00">Kuwait</option>
<option value="+03:00">Nairobi</option>
<option value="+03:00">Riyadh</option>
<option value="+03:00">Moscow</option>
<option value="+03:30">Tehran</option>
<option value="+04:00">Baku</option>
<option value="+04:00">Volgograd</option>
<option value="+04:00">Muscat</option>
<option value="+04:00">Tbilisi</option>
<option value="+04:00">Yerevan</option>
<option value="+04:30">Kabul</option>
<option value="+05:00">Karachi</option>
<option value="+05:00">Tashkent</option>
<option value="+05:30">Kolkata</option>
<option value="+05:45">Kathmandu</option>
<option value="+06:00">Ekaterinburg</option>
<option value="+06:00">Almaty</option>
<option value="+06:00">Dhaka</option>
<option value="+07:00">Novosibirsk</option>
<option value="+07:00">Bangkok</option>
<option value="+07:00">Jakarta</option>
<option value="+08:00">Krasnoyarsk</option>
<option value="+08:00">Chongqing</option>
<option value="+08:00">Hong Kong</option>
<option value="+08:00">Kuala Lumpur</option>
<option value="+08:00">Perth</option>
<option value="+08:00">Singapore</option>
<option value="+08:00">Taipei</option>
<option value="+08:00">Ulaan Bataar</option>
<option value="+08:00">Urumqi</option>
<option value="+09:00">Irkutsk</option>
<option value="+09:00">Seoul</option>
<option value="+09:00">Tokyo</option>
<option value="+09:30">Adelaide</option>
<option value="+09:30">Darwin</option>
<option value="+10:00">Yakutsk</option>
<option value="+10:00">Brisbane</option>
<option value="+10:00">Canberra</option>
<option value="+10:00">Guam</option>
<option value="+10:00">Hobart</option>
<option value="+10:00">Melbourne</option>
<option value="+10:00">Port Moresby</option>
<option value="+10:00">Sydney</option>
<option value="+11:00">Vladivostok</option>
<option value="+12:00">Magadan</option>
<option value="+12:00">Auckland</option>
<option value="+12:00">Fiji"</option>